// Generated by CoffeeScript 2.5.1
(function() {
  //#= require '../../vendor/photoswipe'
  //#= require '../../vendor/photoswipe-ui-default'
  window.Argosity || (window.Argosity = {});

  window.Argosity.Gallery = class Gallery {
    constructor(selector = '.gallery > a', options1 = {}) {
      var el, i, j, len, ref;
      this.options = options1;
      this.slides = [];
      ref = document.querySelectorAll(selector);
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        el = ref[i];
        this.addSlide(el, i);
      }
    }

    onClick(ev, el, index) {
      var gallery, k, options, ref, v;
      ev.preventDefault();
      options = {index};
      ref = this.options;
      for (k in ref) {
        v = ref[k];
        options[k] = v;
      }
      gallery = new PhotoSwipe(document.querySelector('.pswp'), PhotoSwipeUI_Default, this.slides, options);
      return gallery.init();
    }

    addSlide(el, i) {
      el.addEventListener('click', (ev) => {
        return this.onClick(ev, el, i);
      });
      return this.slides.push({
        msrc: el.querySelector('img').src,
        src: el.getAttribute('href'),
        title: el.querySelector('figure').textContent,
        h: el.getAttribute('data-height'),
        w: el.getAttribute('data-width')
      });
    }

  };

}).call(this);
