// Generated by CoffeeScript 2.5.1
(function() {
  //#= require './scroll-link'
  //#= require './contact-form'
  //#= require_self
  window.Argosity || (window.Argosity = {});

  window.Argosity.Jekyll = class Jekyll {
    constructor(options = {}) {
      var contact;
      ({contact} = options);
      document.addEventListener('DOMContentLoaded', () => {
        if (contact) {
          return this.form = new Argosity.ContactForm(contact);
        }
      });
    }

  };

}).call(this);
