// Generated by CoffeeScript 2.5.1
(function() {
  var DEFAULT_DURATION, EASE_IN_OUT, POSITION;

  window.Argosity || (window.Argosity = {});

  DEFAULT_DURATION = 750; // milliseconds

  EASE_IN_OUT = function(t) {
    if (t < .5) {
      return 4 * t * t * t;
    } else {
      return (t - 1) * (2 * t - 2) * (2 * t - 2) + 1;
    }
  };

  POSITION = function(start, end, elapsed, duration) {
    if (elapsed > duration) {
      return end;
    } else {
      return start + (end - start) * EASE_IN_OUT(elapsed / duration);
    }
  };

  window.Argosity.ScrollLink = class ScrollLink {
    constructor(link, destination1, options = {}) {
      this.link = link;
      this.destination = destination1;
      this.options = options;
      if (!(this.destination instanceof Element)) {
        this.destination = document.querySelector(this.destination);
      }
      if (!(this.link instanceof Element)) {
        this.link = document.querySelector(this.link);
      }
      if (this.link && this.destination) {
        this.link.addEventListener('click', () => {
          return this.scrollToElement();
        });
      } else {
        if (typeof console !== "undefined" && console !== null) {
          console.warn("failed to setup link", this.link, this.destination);
        }
      }
    }

    scrollToElement() {
      return this.constructor.scroll(this.destination, this.options.duration || DEFAULT_DURATION);
    }

    static scroll(destination, duration = DEFAULT_DURATION) {
      var endPos, startPos, startTime, step;
      if (!(destination instanceof Element)) {
        destination = document.querySelector(destination);
      }
      if (!destination) {
        if (typeof console !== "undefined" && console !== null) {
          console.warn("failed to scroll to", destination);
        }
        return false;
      }
      startPos = window.pageYOffset;
      endPos = destination.getBoundingClientRect().top - document.body.getBoundingClientRect().top;
      startTime = Date.now();
      step = function() {
        var elapsed;
        elapsed = Date.now() - startTime;
        window.scroll(0, POSITION(startPos, endPos, elapsed, duration));
        if (elapsed < duration) {
          return window.requestAnimationFrame(step);
        }
      };
      return step();
    }

  };

}).call(this);
